# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'machine_a_sous.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(408, 476)
        self.machine = QtWidgets.QLabel(Form)
        self.machine.setGeometry(QtCore.QRect(10, 0, 391, 471))
        self.machine.setText("")
        self.machine.setPixmap(QtGui.QPixmap(":/images/machine.png"))
        self.machine.setObjectName("machine")
        self.reward = QtWidgets.QLCDNumber(Form)
        self.reward.setGeometry(QtCore.QRect(110, 160, 241, 181))
        self.reward.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.reward.setDigitCount(4)
        self.reward.setProperty("intValue", 0)
        self.reward.setObjectName("reward")
        self.text_score = QtWidgets.QLabel(Form)
        self.text_score.setGeometry(QtCore.QRect(130, 30, 71, 61))
        self.text_score.setFocusPolicy(QtCore.Qt.NoFocus)
        self.text_score.setTextFormat(QtCore.Qt.AutoText)
        self.text_score.setWordWrap(False)
        self.text_score.setObjectName("text_score")
        self.score = QtWidgets.QLCDNumber(Form)
        self.score.setGeometry(QtCore.QRect(200, 30, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        self.score.setFont(font)
        self.score.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.score.setAutoFillBackground(False)
        self.score.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.score.setFrameShadow(QtWidgets.QFrame.Raised)
        self.score.setSmallDecimalPoint(False)
        self.score.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.score.setProperty("intValue", 0)
        self.score.setObjectName("score")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 250, 51, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(204, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setTabletTracking(False)
        self.pushButton.setAcceptDrops(False)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton{background-color : #CC3333; border-radius: 10px;}\n"
"QPushButton::pressed{background-color : #CC3353; border-radius: 10px;}")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.reward.raise_()
        self.machine.raise_()
        self.text_score.raise_()
        self.score.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setFixedSize(408, 476)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.text_score.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt;\">Score : </span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Tirez"))
import images.resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
